### PR TITLE
Minor README improvements

### PR DESCRIPTION
**Pull request by hobarrera**
A couple of tiny improvements, including documenting the minimum required versions (as seen in #20).

### CODE REVIEW

**Comment by JacobMillward** [comment]
+1

**Comment by slashrsm** [comment]
Looks good to me.

**Comment by franciscoj** [comment]
:+1:

**Comment by patjak** [comment]
Thanks for the pull request but I'd prefer if we have information like this in the wiki instead. Could you please add it there? The wiki is open for anyone to edit and is easier to organize.

**Comment by hobarrera** [comment]
@patjak I've updated this PR to remove some redundant information from the README and simply point users to the wiki. I've also added (and updated) that information from the wiki.

**Comment by patjak** [comment]
Looks good, thanks.

**Pull request merged**
