### PR TITLE
Add universal extraction script for both OS X and Windows drivers

### PR DESCRIPTION
**Pull request by mauritiusdadd**
Following from [my previous comment] (https://github.com/patjak/bcwc_pcie/issues/15#issuecomment-166859154) on issue #15: I added also the hashes for the version 1.05 of the driver, so I think it could be included into the main repo.

### CODE REVIEW

**Comment by wvengen** [comment]
:+1:

**Comment by patjak** [comment]
We shouldn't expose the windows driver extraction yet since it's not working and seems to confuse people atm. If we do expose it at a later time we should also try to automate the download and unpacking. It would also be nice to have an --install option that copies the firmware to it's proper directory.

**Comment by wvengen** [comment]
What about keeping that hashes and file offsets, and showing a message that the El Capitan driver is needed when another is detected?

**Comment by mauritiusdadd** [comment]
@patjak: Ok, I understand. It seems that we could download the OS X driver from the Apple Download Centre (see #14 comment [167223818] (https://github.com/patjak/bcwc_pcie/issues/14#issuecomment-167223818)). If that's possible, I will update the script and add the capabilities to download the driver and install the extracted firmware. For this reason, I'm going to close this pull request and I will make a new one with the updated script.

**Pull request closed without merging**
