### PR TITLE
add dkms support

### PR DESCRIPTION
**Pull request by mmlb**

### CODE REVIEW

**Comment by mmlb** [comment]
@patjak ping?

**Comment by patjak** [comment]
Hmm, this will install the module in /lib/module/<kernel-version>/extra/$pwd. Is that really the default behaviour?

**Comment by mmlb** [comment]
Not quite, I'm getting `/lib/modules/$(uname -r)/extra/facetimehd.ko.gz`, you can test it out by doing
```
make INSTALL_MOD_PATH=$PWD/destdir install
```
I'm pretty sure the build system figures it out from `obj-m`.

I made the makefile by mashing
http://lxr.free-electrons.com/source/Documentation/kbuild/modules.txt#L102 together with 
http://lxr.free-electrons.com/source/Documentation/kbuild/modules.txt#L175

**Comment by mmlb** [comment]
ping @patjak ?

**Comment by patjak** [comment]
Sorry for the delay. ```make install```with this patch applied installed in the wrong directory for me so something is wrong.

**Comment by mmlb** [comment]
@patjak no worries, I probably should have closed this in favor of #73 already being merged in

**Pull request closed without merging**
