### PR TITLE
facetimehd: fix fthd_hw_ddr_rewrite_mode_regs()

### PR DESCRIPTION
**Pull request by askulysh**
I've got correct values from
4e1d11e205e5c55d128efa0029b268fe firmware.
It resolves issue #35

Signed-off-by: Andriy Skulysh <askulysh@gmail.com>

### CODE REVIEW

**Comment by yaguphire** [comment]
i confirm success.

**Comment by patjak** [comment]
Seems to cause no harm on my system. In what driver did you find this change (OSX / Windows / version)?

**Comment by askulysh** [comment]
AppleCameraInterface from osxupd10.11.2.dmg

**Comment by patjak** [comment]
Merged. Thanks for the fix.

**Comment by yaguphire** [comment]
@askulysh where can you find osxupd10.11.2.dmg?  I pulled the firmware from a fresh install of OS X 10.11.2 ;

**Pull request merged**
