### PR TITLE
Add 'make deb' to make debian firmware package.

### PR DESCRIPTION
**Pull request by nbartos**

### CODE REVIEW

**Comment by nbartos** [comment]
Any chance I can get a merge on this?  If not, I'll just close this PR and maintain my patch in my fork.

**Comment by patjak** [comment]
Looks good but is the "Section" really correct in control.template? Perhaps there is a special section for firmwares?

**Comment by nbartos** [comment]
I used the same Section as linux-firmware (what owns /lib/firmware).
```
$ apt-cache show 8812au-dkms  | grep Section
Section: misc

$ apt-cache show linux-firmware | grep Section
Section: misc
```

**Comment by patjak** [comment]
Ok, sounds good. Merged. Thanks.

**Pull request merged**
